=== argusiot/data_platform/quilt/argus_quilt/SCHEMA_DEFN_state_set.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://json-schema.org/draft-07/schema#",
    "title" : "State Set JSON schema definition",
    "description" : "This scheme defines how a state set should be defined.",
    "schema_version" : 1.0,

    "definitions" : {
        "output_state_ts_defn" : {
            "type" : "object",
             "properties" : {
                 "metric" : { "type" : "string" },
                 "tags" : { "type" : "object", "properties": {"state_label" : {"enum" : ["PLACEHOLDER"]}}, "required" : ["state_label"]}
              },
              "required" : ["metric", "tags"]
        },
         "ts_leaf_defn" : {
             "type" : "object",
             "properties" : {
                 "metric" : { "type" : "string" },
                 "tags" : { "type" : "object" }
              },
              "required" : ["metric", "tags"]
         },

        "fq_timeseries" : {
            "type" : "object",
            "properties" : {
                "ts_name" : { "type" : "string"},
                "ts_defn" : {
                    "$ref" : "#/definitions/ts_leaf_defn"
                }
            },
            "required" : ["ts_name", "ts_defn"]
        },

        "statement" : {
            "type" : "array",
            "items" : [
                { "type" : "string" },
                { "type" : "string",
                  "enum" : ["<", ">", "==", "<=", ">="] },
                {
                    "anyOf": [
                        { "type" : "number" },
                        { "type" : "integer" }
                    ]
                }
            ]
        },

        "state_defn" : {
            "type" : "object",
            "properties" : {
                "label" : { "type" : "string" },
                "expression" : {
                    "type" : "array",
                    "items": {
                        "$ref" : "#/definitions/statement"
                    }
                },
                "expression_operator" : { "const": "AND"}
            }
        }
    },

    "type" : "object",
    "properties" : {
        "name" : { "type" : "string" },
        "uuid" : { "type" : "string" },
        "state_definitions" : {
            "type" : "array",
            "items": {
                "$ref" : "#/definitions/state_defn"
            }
        },
	"query_params" : {
            "type" : "object",
	    "properties" : {
	        "msec_response" : {
                    "type" : "boolean",
	            "default": false
		}
	    },
            "required" : ["msec_response"]
	},
        "input_timeseries" : {
            "type" : "array",
            "items": {
                "$ref" : "#/definitions/fq_timeseries"
            }
        },
        "output_timeseries_template" : {
            "type" : "object",
            "$ref" : "#/definitions/output_state_ts_defn"
        }
    },
    "required" : ["name", "uuid", "state_definitions", "input_timeseries", "output_timeseries_template"]
}

=== argusiot/data_platform/quilt_demos/extruder_states_fine.json
{
        "name": "extruder_states",
        "uuid": "xxxxxxxxxxxxxxx",
        "state_definitions" : [
            {
               "label" : "POWER_OFF",
               "expression" : [
                 ["machine_power", "<", 1],
                 ["melt_temperature", "<=", 200]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "PRODUCING",
               "expression" : [
                 ["machine_power", "==", 1],
                 ["melt_temperature", ">=", 115],
                 ["screw_speed", ">=", 10],
                 ["line_speed", ">=", 5]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "IDLING2",
               "expression" : [
                 ["machine_power", "==", 1],
                 ["melt_temperature", ">=", 115],
                 ["screw_speed", "<", 10]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "PURGING",
               "expression" : [
                 ["machine_power", "==", 1],
                 ["melt_temperature", ">=", 115],
                 ["screw_speed", ">=", 10],
                 ["line_speed", "<", 5]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "IDLING1",
               "expression" : [
                 ["machine_power", "==", 1],
                 ["melt_temperature", "<", 115]
               ],
               "expression_operator" : "AND"
            }
        ],
        "input_timeseries" : [
            {
                "ts_name" : "melt_temperature",
                "ts_defn" : {
                    "metric": "machine.sensor.melt_temperature",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "deg_C",
			       "port_num": "1",
			       "machine_name" : "90mm_extruder",
			       "machine_location" : "SIN",
			       "machine_site" : "WCPL-1"
		             }
                }
            },
            {
                "ts_name" : "machine_power",
                "ts_defn" : {
                    "metric": "machine.sensor.machine_powerOn_state",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "Binary",
			       "port_num": "5",
			       "machine_name" : "90mm_extruder",
			       "machine_location" : "SIN",
			       "machine_site" : "WCPL-1"
		             }
                }
            },
            {
                "ts_name" : "screw_speed",
                "ts_defn" : {
                    "metric": "machine.sensor.screw_speed",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "RPM",
			       "port_num": "3",
			       "machine_name" : "90mm_extruder",
			       "machine_location" : "SIN",
			       "machine_site" : "WCPL-1"
		             }
                }
            },
            {
                "ts_name" : "line_speed",
                "ts_defn" : {
                    "metric": "machine.sensor.line_speed",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "meters_per_sec",
			       "port_num": "4",
			       "machine_name" : "90mm_extruder",
			       "machine_location" : "SIN",
			       "machine_site" : "WCPL-1"
		             }
                }
            }
        ],
        "output_timeseries_template" : {
            "metric" : "quilt.extruder_states_fine",
            "tags" : { "machine" : "90mm_extruder", "state_label" : "PLACEHOLDER" }
        }
}

=== argusiot/data_platform/quilt_demos/extruder_states_coarse_msec.json
{
        "name": "extruder_states",
        "uuid": "xxxxxxxxxxxxxxx",
        "state_definitions" : [
            {
               "label" : "ON_Producing",
               "expression" : [
                 ["machine_power", "==", 1],
                 ["melt_temperature", ">=", 115]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "ON_Overhead",
               "expression" : [
                 ["machine_power", "==", 1],
                 ["melt_temperature", "<", 115]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "Power_OFF",
               "expression" : [
                 ["machine_power", "<", 1],
                 ["melt_temperature", "<=", 200]
               ],
               "expression_operator" : "AND"
            }
        ],
	"query_params" : {
	    "msec_response": true
	},
        "input_timeseries" : [
            {
                "ts_name" : "melt_temperature",
                "ts_defn" : {
                    "metric": "machine.sensor.melt_temperature",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "deg_C",
			       "port_num": "1",
			       "machine_name" : "90mm_extruder",
			       "machine_location" : "SIN",
			       "machine_site" : "WCPL-1"
		             }
                }
            },
                      {
                "ts_name" : "machine_power",
                "ts_defn" : {
                    "metric": "machine.sensor.machine_powerOn_state",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "Binary",
			       "port_num": "5",
			       "machine_name" : "90mm_extruder",
			       "machine_location" : "SIN",
			       "machine_site" : "WCPL-1"
		             }
                }
            }
        ],
        "output_timeseries_template" : {
            "metric" : "quilt.extruder_states_coarse_msec",
            "tags" : { "machine" : "90mm_extruder", "state_label" : "PLACEHOLDER" }
        }
}

=== argusiot/data_platform/quilt_demos/steel_poc_plate_thickness_states.json
{
    "name": "plate_thickness_states",
    "uuid": "xxxxxxxxxxxxxxx",
    "state_definitions" : [
        {
            "label" : "Excellent_Plate_Thick_All",
            "expression" : [
                ["NE_thickness", "<", 1.00005],
                ["NE_thickness", ">", 0.99995],
                ["SE_thickness", "<", 1.00005],
                ["SE_thickness", ">", 0.99995],
                ["NW_thickness", "<", 1.00005],
                ["NW_thickness", ">", 0.99995],
                ["SW_thickness", "<", 1.00005],
                ["SW_thickness", ">", 0.99995]
            ],
            "expression_operator" : "AND"
        }
    ],
    "input_timeseries" : [
        {
            "ts_name" : "NE_thickness",
            "ts_defn" : {
                "metric": "poc.v3.ne.plate.thickness.n9-5",
                "tags" : {
                    "machine_id": "106-5",
                    "unit": "inch"
                }
            }
        },
        {
            "ts_name" : "SE_thickness",
            "ts_defn" : {
                "metric": "poc.v3.se.plate.thickness.n9-9",
                "tags" : {
                    "machine_id": "106-9",
                    "unit": "inch"
                }
            }
        },
        {
            "ts_name" : "NW_thickness",
            "ts_defn" : {
                "metric": "poc.v3.nw.plate.thickness.n9-13",
                "tags" : {
                    "machine_id": "106-13",
                    "unit": "inch"
                }
            }
        },
        {
            "ts_name" : "SW_thickness",
            "ts_defn" : {
                "metric": "poc.v3.sw.plate.thickness.n9-17",
                "tags" : {
                    "machine_id": "106-17",
                    "unit": "inch"
                }
            }
        }
    ],
    "output_timeseries_template" : {
        "metric" : "quilt.test_state_plate_spec",
        "tags" : { "machine" : "106", "state_label" : "PLACEHOLDER" }
    }
}

=== argusiot/data_platform/quilt_demos/quilt_test_state_v1_definition.json
{
        "name": "extruder_states",
        "uuid": "xxxxxxxxxxxxxxx",
        "state_definitions" : [
            {
               "label" : "TestStateV1_ON_Producing",
               "expression" : [
                 ["machine_power", "==", 1],
                 ["melt_temperature", ">=", 115]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "TestStateV1_ON_Overhead",
               "expression" : [
                 ["machine_power", "==", 1],
                 ["melt_temperature", "<", 115]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "TestStateV1_MachineOFF",
               "expression" : [
                 ["machine_power", "<", 1],
                 ["melt_temperature", "<=", 200]
               ],
               "expression_operator" : "AND"
            }
        ],
        "input_timeseries" : [
            {
                "ts_name" : "melt_temperature",
                "ts_defn" : {
                    "metric": "machine.sensor.melt_temperature",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "deg_C",
			       "shift_id": "1",
			       "port_num": "1",
			       "industry": "WIRE_AND_CABLE_MANUFACTURING",
			       "machine_name" : "90mm_extruder"
		             }
                }
            },
                      {
                "ts_name" : "machine_power",
                "ts_defn" : {
                    "metric": "machine.sensor.machine_powerOn_state",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "Binary",
			       "shift_id": "1",
			       "port_num": "5",
			       "industry": "WIRE_AND_CABLE_MANUFACTURING",
			       "machine_name" : "90mm_extruder"
		             }
                }
            }
        ],
        "output_timeseries_template" : {
            "metric" : "quilt.test_state_v1",
            "tags" : { "machine" : "90mm_extruder", "state_label" : "PLACEHOLDER" }
        }
}

=== argusiot/data_platform/quilt_demos/extruder_states.json
{
        "name": "extruder_states",
        "uuid": "xxxxxxxxxxxxxxx",
        "state_definitions" : [
            {
               "label" : "PRODUCING",
               "expression" : [
                 ["machine_power", "==", 1],
                 ["melt_temperature", ">=", 115],
                 ["screw_speed", ">=", 10],
                 ["line_speed", ">=", 15]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "IDLING",
               "expression" : [
                 ["machine_power", "==", 1],
                 ["melt_temperature", "<", 115],
                 ["screw_speed", ">=", 0],
                 ["line_speed", ">=", 0]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "PURGING",
               "expression" : [
                 ["machine_power", "==", 1],
                 ["melt_temperature", "<", 115],
                 ["screw_speed", ">", 10],
                 ["line_speed", ">", 0]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "POWER_OFF",
               "expression" : [
                 ["machine_power", "<", 1],
                 ["melt_temperature", "<=", 200]
               ],
               "expression_operator" : "AND"
            }
        ],
        "input_timeseries" : [
            {
                "ts_name" : "melt_temperature",
                "ts_defn" : {
                    "metric": "machine.sensor.melt_temperature",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "deg_C",
			       "shift_id": "1",
			       "port_num": "1",
			       "industry": "WIRE_AND_CABLE_MANUFACTURING",
			       "machine_name" : "90mm_extruder"
		             }
                }
            },
            {
                "ts_name" : "machine_power",
                "ts_defn" : {
                    "metric": "machine.sensor.machine_powerOn_state",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "Binary",
			       "shift_id": "1",
			       "port_num": "5",
			       "industry": "WIRE_AND_CABLE_MANUFACTURING",
			       "machine_name" : "90mm_extruder"
		             }
                }
            },
            {
                "ts_name" : "screw_speed",
                "ts_defn" : {
                    "metric": "machine.sensor.screw_speed",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "Binary",
			       "shift_id": "1",
			       "port_num": "3",
			       "industry": "WIRE_AND_CABLE_MANUFACTURING",
			       "machine_name" : "90mm_extruder"
		             }
                }
            },
            {
                "ts_name" : "line_speed",
                "ts_defn" : {
                    "metric": "machine.sensor.line_speed",
                    "tags" : {
		               "machine_type": "EXTRUDER",
			       "unit": "Binary",
			       "shift_id": "1",
			       "port_num": "4",
			       "industry": "WIRE_AND_CABLE_MANUFACTURING",
			       "machine_name" : "90mm_extruder"
		             }
                }
            }
        ],
        "output_timeseries_template" : {
            "metric" : "quilt.extruder_states_v1",
            "tags" : { "machine" : "90mm_extruder", "state_label" : "PLACEHOLDER" }
        }
}

=== argusiot/data_platform/quilt_demos/quilt_test_state_v1_definition_ulfs.json
{
        "name": "power_flow_states",
        "uuid": "xxxxxxxxxxxxxxx",
        "state_definitions" : [
            {
               "label" : "TestStateV1_ON_Producing",
               "expression" : [
                 ["R2_power", ">", 5000],
                 ["descaler_flow", ">=", 300]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "TestStateV1_ON_Overhead",
               "expression" : [
                 ["R2_power", ">", 5000],
                 ["descaler_flow", "<", 300]
               ],
               "expression_operator" : "AND"
            },
            {
               "label" : "TestStateV1_MachineOFF",
               "expression" : [
                 ["R2_power", "<=", 5000],
                 ["descaler_flow", "<", 300]
               ],
               "expression_operator" : "AND"
            }
        ],
        "input_timeseries" : [
            {
                "ts_name" : "descaler_flow",
                "ts_defn" : {
                    "metric": "poc.v3.f1.descale.chiller.header.flow",
                    "tags" : {
		               "machine_id": "106-25",
			       "unit": "gpm"
		             }
                }
            },
                      {
                "ts_name" : "R2_power",
                "ts_defn" : {
                    "metric": "poc.v3.r2.power.n9-33",
                    "tags" : {
		               "machine_id": "106-33",
			       "unit": "KW"
		             }
                }
            }
        ],
        "output_timeseries_template" : {
            "metric" : "quilt.test_state_flow_power",
            "tags" : { "machine" : "106", "state_label" : "PLACEHOLDER" }
        }
}

=== argusiot/data_platform/quilt_demos/quilt_steel_poc_state_def_plate_thickness.json
{
    "name": "plate_thickness_states",
    "uuid": "xxxxxxxxxxxxxxx",
    "state_definitions" : [
        {
            "label" : "Excellent_Plate_Thick_All",
            "expression" : [
                ["NE_thickness", "<", 1.00005],
                ["NE_thickness", ">", 0.99995],
                ["SE_thickness", "<", 1.00005],
                ["SE_thickness", ">", 0.99995],
                ["NW_thickness", "<", 1.00005],
                ["NW_thickness", ">", 0.99995],
                ["SW_thickness", "<", 1.00005],
                ["SW_thickness", ">", 0.99995]
            ],
            "expression_operator" : "AND"
        },
        {
            "label" : "LGood_Plate_Thick_NE",
            "expression" : [
                ["NE_thickness", "<=", 0.99995],
                ["NE_thickness", ">",  0.99990]
            ],
            "expression_operator" : "AND"
        },
        {
            "label" : "LGood_Plate_Thick_SE",
            "expression" : [
                ["SE_thickness", "<=", 0.99995],
                ["SE_thickness", ">",  0.99990]
            ],
            "expression_operator" : "AND"
        },
        {
            "label" : "LGood_Plate_Thick_NW",
            "expression" : [
                ["NW_thickness", "<=", 0.99995],
                ["NW_thickness", ">",  0.99990]
            ],
            "expression_operator" : "AND"
        },
        {
            "label" : "LGood_Plate_Thick_SW",
            "expression" : [
                ["SW_thickness", "<=", 0.99995],
                ["SW_thickness", ">",  0.99990]
            ],
            "expression_operator" : "AND"
        },
        {
            "label" : "HGood_Plate_Thick_NE",
            "expression" : [
                ["NE_thickness", "<",  1.00010],
                ["NE_thickness", ">=", 1.00005]
            ],
            "expression_operator" : "AND"
        },
        {
            "label" : "HGood_Plate_Thick_SE",
            "expression" : [
                ["SE_thickness", "<",  1.00010],
                ["SE_thickness", ">=", 1.00005]
            ],
            "expression_operator" : "AND"
        },
        {
            "label" : "HGood_Plate_Thick_NW",
            "expression" : [
                ["NW_thickness", "<",  1.00010],
                ["NW_thickness", ">=", 1.00005]
            ],
            "expression_operator" : "AND"
        },
        {
            "label" : "HGood_Plate_Thick_SW",
            "expression" : [
                ["SW_thickness", "<",  1.00010],
                ["SW_thickness", ">=", 1.00005]
            ],
            "expression_operator" : "AND"
        },
        {
            "label" : "Bad_Plate_Thick_All",
            "expression" : [
                ["NE_thickness", ">=", 1.00010],
                ["NE_thickness", "<=", 0.99990],
                ["SE_thickness", ">=", 1.00010],
                ["SE_thickness", "<=", 0.99990],
                ["NW_thickness", ">=", 1.00010],
                ["NW_thickness", "<=", 0.99990],
                ["SW_thickness", ">=", 1.00010],
                ["SW_thickness", "<=", 0.99990]
            ],
            "expression_operator" : "AND"
        }
    ],
    "input_timeseries" : [
        {
            "ts_name" : "NE_thickness",
            "ts_defn" : {
                "metric": "poc.v3.ne.plate.thickness.n9-5",
                "tags" : {
                    "machine_id": "106-5",
                    "unit": "inch"
                }
            }
        },
        {
            "ts_name" : "SE_thickness",
            "ts_defn" : {
                "metric": "poc.v3.se.plate.thickness.n9-9",
                "tags" : {
                    "machine_id": "106-9",
                    "unit": "inch"
                }
            }
        },
        {
            "ts_name" : "NW_thickness",
            "ts_defn" : {
                "metric": "poc.v3.nw.plate.thickness.n9-13",
                "tags" : {
                    "machine_id": "106-13",
                    "unit": "inch"
                }
            }
        },
        {
            "ts_name" : "SW_thickness",
            "ts_defn" : {
                "metric": "poc.v3.sw.plate.thickness.n9-17",
                "tags" : {
                    "machine_id": "106-17",
                    "unit": "inch"
                }
            }
        }
    ],
    "output_timeseries_template" : {
        "metric" : "quilt.test_state_plate_spec",
        "tags" : { "machine" : "106", "state_label" : "PLACEHOLDER" }
    }
}

=== argusiot/data_platform/quilt_demos/steel_demo_pyro_flicker_states.json
{
    "name": "plate_pyro_states",
    "uuid": "xxxxxxxxxxxxxxx",
    "state_definitions" : [
        {
            "label" : "Plate_Pyro_Fluctuation",
            "expression" : [
                ["bank10E_pyro", "<", 1080],
                ["bank10E_present", ">", 0.5]
            ],
            "expression_operator" : "AND"
        }
    ],
    "input_timeseries" : [
        {
            "ts_name" : "bank10E_pyro",
            "ts_defn" : {
                "metric": "poc.v3.bank.10.east.pyro",
                "tags" : {
                    "machine_id": "107-64",
                    "unit": "F"
                }
            }
        },
        {
            "ts_name" : "bank10E_present",
            "ts_defn" : {
                "metric": "poc.v3.bank.10.east.pyro.metal.present",
                "tags" : {
                    "machine_id": "107.356"
                }
            }
        }
    ],
    "output_timeseries_template" : {
        "metric" : "quilt.test_state_plate_pyro_spec",
        "tags" : { "machine" : "bank10E", "state_label" : "PLACEHOLDER" }
    }
}
